[package]
name = "resampler-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rand = "0.8.5"
rubato = "0.14.1"
tokio = { version = "1.33.0", features = ["full"] }
